# Generated by Django 4.2.3 on 2023-07-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_management', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='format',
            field=models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('txt', 'TXT'), ('file', 'FILE')], max_length=10),
        ),
    ]
