# Generated by Django 4.2.3 on 2023-07-22 09:12

from django.db import migrations, models
import document_management.validators


class Migration(migrations.Migration):

    dependencies = [
        ('document_management', '0004_alter_document_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/', validators=[document_management.validators.FileValidator(allowed_formats=['.pdf', '.docx', '.txt'], max_size=10485760)]),
        ),
    ]
