# Generated by Django 4.2.3 on 2023-07-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_management', '0005_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
